### ISSUE TITLE
Class Cast Exception

### ISSUE THREAD

**Issue by dariusc93** [MyEssentials/MyTown-1.5.2#4]
For some reason, the Entity e doesnt/cannot be cast to IExplosiveCart. I will likely submit a PR for this soon after I reproduce it. This is is just for reference. If the developer fix it before I do, I will still likely submit a PR to change how it is it is cast.  

java.lang.ClassCastException: mods.railcraft.common.carts.EntityCartTNT cannot be cast to railcraft.common.api.carts.IExplosiveCart
 at ee.lutsu.alpha.mc.mytown.event.prot.RailCraft.update(RailCraft.java:42)
 at ee.lutsu.alpha.mc.mytown.event.ProtectionEvents.tickStart(ProtectionEvents.java:199)
 at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:28)
 at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
 at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:295)
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:822)
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:320)
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:732)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:614)
 at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by jgoett154** [comment]
I had seen this was happening and think I have a fix, just haven't submitted it yet since I am working on some major changes to MyTown. But your more than welcome to submit a PR :)
